name: Release
on:  
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Run the Gradle package task
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: publish -Pversion=${{github.ref_name}}
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
        name: "Release: v${{github.ref_name}}"
        allowUpdates: true
        generateReleaseNotes: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        artifacts: "build/libs/intellij-codeceptjs-*.jar"